name: Push
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: "[Prepare]: Build KinD cluster"
      run: |
        kind version
        kind create cluster --loglevel debug --wait=5m
        kind get kubeconfig --internal >$HOME/.kube/config

    - name: "[Prepare]: Getting nodes"
      run: |
        kubectl get nodes

    - name: "[Prepare]: Setting up kubeconfig ENV for Github Chaos Action"
      run: echo ::set-env name=KUBE_CONFIG_DATA::$(base64 -w 0 ~/.kube/config)
  
    - name: "[Prepare]: Launch the test application from deploy repo"
      run: |
        kubectl apply -f https://raw.githubusercontent.com/ksatchit/test-k8s-deploy/master/test-k8s-app/hello-deploy.yaml
        kubectl apply -f https://raw.githubusercontent.com/ksatchit/test-k8s-deploy/master/test-k8s-app/hello-service.yaml

    - name: "[Status]: Waiting for app pod to come in Running state"
      run: |
        bash ./litmus/status-check.sh
        kubectl get pods
      env: 
        APP_LABEL: name=hello
        APP_NS: default
       
    - name: "[Inject]: Running pod delete chaos experiment"
      uses: mayadata-io/github-chaos-actions@v0.1.0
      env:
        INSTALL_LITMUS: true
        APP_NS: default
        APP_LABEL: name=hello
        APP_KIND: deployment
        EXPERIMENT_NAME: pod-delete
        EXPERIMENT_IMAGE: litmuschaos/ansible-runner:latest        
        TOTAL_CHAOS_DURATION: 20
        CHAOS_INTERVAL: 10
        FORCE: false
        LITMUS_CLEANUP: true

    - name: "[Cleanup]: Tear down hello-app deployment"
      run: |
        kubectl delete -f https://raw.githubusercontent.com/ksatchit/test-k8s-deploy/master/test-k8s-app/hello-deploy.yaml
        kubectl delete -f https://raw.githubusercontent.com/ksatchit/test-k8s-deploy/master/test-k8s-app/hello-service.yaml

  report:  
    runs-on: ubuntu-latest
    steps: 

    - name: "[Report]: Update baseline YAML with tested images"
      run: |
        # TEMP
        kubectl apply -f https://raw.githubusercontent.com/ksatchit/test-k8s-deploy/master/test-k8s-app/hello-deploy.yaml --dry-run -o jsonpath='{.spec.template.spec.containers[?(@.name=="test-app")].image}' | cut -d "/" -f 2
